apiVersion: v1
kind: Service
metadata:
  name: te-agent-boutique
  labels:
    app: te-agent-boutique
spec:
  ports:
  - port: 80
    name: web
  - port: 443
    name: https
  clusterIP: None
  selector:
    app: te-agent-boutique
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: te-agent-boutique
spec:
  selector:
    matchLabels:
      app: te-agent-boutique
  replicas: 1
  serviceName: "te-agent-boutique"
  template:
    metadata:
      labels:
        app: te-agent-boutique
    spec:
      # nodeSelector:
      #   cloud.google.com/gke-nodepool: pool-1
      affinity:
        # Ensure this ThousandEyes Agent deploys on node that 
        # the "paymentservice" app is running on.
        podAffinity: 
          requiredDuringSchedulingIgnoredDuringExecution: 
          - labelSelector:
              matchExpressions:
              - key: app 
                operator: In 
                values:
                - paymentservice 
            topologyKey: failure-domain.beta.kubernetes.io/zone
      containers:
      - name: te-agent-boutique
        image: thousandeyes/enterprise-agent:latest
        command: ["/sbin/my_init"]
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_ADMIN
        env:
          - name: TEAGENT_ACCOUNT_TOKEN
            valueFrom:
              secretKeyRef:
                name: boutique-credentials
                key: TEAGENT_ACCOUNT_TOKEN
          - name: TEAGENT_INET
            value: "4"
          - name: KUBERNETES
            value: "true"
        resources:
          requests:
            memory: "2Gi"
            cpu: "200m"
          limits:
            memory: "2Gi"
            cpu: "200m"
        tty: true
        volumeMounts:
          - name: vol-agent
            mountPath: /var/lib/te-agent
          - name: vol-bot
            mountPath: /var/lib/te-browserbot
          - name: vol-log
            mountPath: /var/log/agent
      volumes:
        - name: vol-agent
          persistentVolumeClaim:
            claimName: te-agent-boutique-claim
        - name: vol-log
          hostPath:
            path: /var/thousandeyes/te-agent-boutique/log/
            type: DirectoryOrCreate
        - name: vol-bot
          hostPath:
            path: /var/thousandeyes/te-agent-boutique/te-browserbot/
            type: DirectoryOrCreate
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: te-agent-boutique-vol
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: /var/thousandeyes/te-agent-boutique/te-agent
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: te-agent-boutique-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: te-agent-boutique-vol